import Page from "../[nickname]/page";
import "../globals.css";
import "/public/assets/css/style.css";
import {getGitHubConfig} from "@/lib/github";

export const metadata = {
    title: "User Profile",
    description: "Generated by BitWave Bio",
};

export default async function RootLayout({ params }) {
    const user = await getGitHubConfig(params.nickname);
    return (
      <html lang="en">
      <body>
          <Page params={params} user={user} />
      </body>
      </html>
    );
}
